name: Compatibility Tests
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ng: [8.0, 8.1, 9.0, 9.1]
        ngrx: [8.0, 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 9.0, 9.1, 9.2]
      exclude:
        - ngrx: [9.0, 9.1, 9.2]
          ng: [8.0, 8.1, 8.2]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.ng }}-${{ matrix.ngrx }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ matrix.ng }}-
      - run: |
          yarn install --frozen-lockfile
          yarn add @ngrx/store@${{ matrix.ngrx }} @ngrx/effects@${{ matrix.ngrx }} @angular/core${{ matrix.ng }}
      - run: |
          yarn lint
