name: Compatibility Tests
on: [push]

jobs:
  matrix_prep:
    # Using a separate job and agent so as to be able to use tools like 'sed' and 'jq'
    runs-on: ubuntu-latest
    # Defining outputs of a job allows for easier consumption and use
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      # Checking out code as the set-matrix step utilizes a file named matrix_includes.json
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - id: set-matrix
        run: |
          echo ::set-output name=matrix::{\"include\":$(node dep_matrix.js 9.0 9.1 9.2 10.0 10.1 10.2 11.0 11.1 11.2)}\"

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: matrix_prep
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ matrix.ng }}-${{ matrix.ngrx }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ matrix.ng }}-
      - run: |
          yarn install --frozen-lockfile
          yarn add @ngrx/store@${{ matrix.ngrx }} @ngrx/effects@${{ matrix.ngrx }} @angular/core@${{ matrix.ng }}
      - run: |
          yarn lint
